apiVersion: v1
kind: Service
metadata:
  name: hn-svc
spec:
  type: NodePort
  ports:
  - port: 9000 # port exposed
    targetPort: 80 # container port mapped
    protocol: TCP
  selector:
    app: hello-nginx
